<?php
$this->title = "Users";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'users','action'=>'add'));?>">Add new album</a></p>
<table border=1>
<tr>
<th>id</th>
<th>name</th>
<th>email</th>
<th>password</th>
<th>address</th>
<th>description</th>
<th>sex</th>
<th>city</th>
<th>pets</th>
<th>sports</th>
<th>submit</th>
<th>photo</th>
<th>options</th>
</tr>
<?php

//Show user table
//veremos como pasar bien el array a la vista (ahora funciona por que lo incluse users.php)
foreach($this->users as $key => $user):?>
	<tr>
	<?php
		// for each user line	
		foreach($user as $key1 =>$value):?>
			<td><?=$value;?></td>
		<?php endforeach;?>
		<td>
			<a href="<?php echo $this->url(array('controller'=>'users','action'=>'edit', 'id'=>$user->iduser));?>">Edit</a>
				&nbsp;
			<a href="<?php echo $this->url(array('controller'=>'users','action'=>'delete', 'id'=>$user->iduser));?>">Delete</a>
		</td>		
	</tr>
<?php endforeach;?>
</table>